apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
  labels:
    app: storage
spec:
  containers:
  - name: nginx
    image: vials/test:latest
    imagePullPolicy: Always
    readinessProbe:
      httpGet:
        path: /
        port: 8000
    livenessProbe:
      tcpSocket: { port: 8000 }
    volumeMounts:
    - name: app
      mountPath: /app
    - name: hostpath
      mountPath: /data
  initContainers:
  - name: init-test
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}
  - name: hostpath
    persistentVolumeClaim:
      claimName: storage-pvc
    
