---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view
  namespace: dev
rules:         
  - apiGroups:  
      - ''      
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-view
  namespace: dev
subjects:
- kind: User
  name: ken
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: view
  apiGroup: rbac.authorization.k8s.io