---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus:viewer
rules:         
  - apiGroups:  
      - ''      
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-viewer
subjects:
- kind: Group
  name: system:serviceaccounts:prometheus
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: prometheus:viewer
  apiGroup: rbac.authorization.k8s.io