apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: web-nginx
spec:
  selector:
    app: web-nginx
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: nginx-exporter
      port: 9113
      protocol: TCP
      targetPort: 9113