{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- with .Values.ingress.annotations }}
  annotations: {{- toYaml . | nindent 8 }}
  {{- end }}
  labels:
    app.kubernetes.io/instance: ingress-frontend
  name: ingress-frontend
  namespace: hipster-shop
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{.Values.name}}
                port:
                  number: {{.Values.service.port | default 80 }}
            path: /(.*)
            pathType: {{.Values.service.pathType | default "ImplementationSpecific"}}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
{{- end }}